import {
  TuiAccordionModule,
  TuiArrowModule,
  TuiBadgedContentModule,
  TuiBadgeModule,
  TuiCheckboxLabeledModule,
  TuiDataListDropdownManagerModule,
  TuiDataListWrapperModule,
  TuiFieldErrorPipeModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputFilesModule,
  TuiInputModule,
  TuiInputNumberModule,
  TuiInputPasswordModule,
  TuiIslandModule,
  TuiLineClampModule,
  TuiMultiSelectModule,
  TuiRadioBlockModule,
  TuiSelectModule,
  TuiStepperModule,
  TuiTabsModule,
  TuiTagModule,
  TuiTextAreaModule,
  TuiTilesModule,
  TuiToggleModule,
} from '@taiga-ui/kit';
import {
  TuiAlertModule,
  TuiButtonModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiGroupModule,
  TuiHintModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiModeModule,
  TuiNotificationModule,
  TuiRootModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
  TuiThemeNightModule,
} from '@taiga-ui/core';
import { TuiActiveZoneModule, TuiAutoFocusModule, TuiLetModule } from '@taiga-ui/cdk';
import { TuiCurrencyPipeModule } from '@taiga-ui/addon-commerce';
import { TuiTableModule } from '@taiga-ui/addon-table';
import { TuiAppBarModule, TuiSheetModule } from '@taiga-ui/addon-mobile';
import { PolymorpheusModule } from '@tinkoff/ng-polymorpheus';
import { TuiBlockStatusModule } from '@taiga-ui/layout';

export const TUI_MODULES = [
  TuiInputModule,
  TuiTextfieldControllerModule,
  TuiSvgModule,
  TuiInputPasswordModule,
  TuiIslandModule,
  TuiButtonModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiDropdownModule,
  TuiHostedDropdownModule,
  TuiDataListDropdownManagerModule,
  TuiArrowModule,
  TuiDataListModule,
  TuiCheckboxLabeledModule,
  TuiSelectModule,
  TuiGroupModule,
  TuiRadioBlockModule,
  TuiInputDateModule,
  TuiInputNumberModule,
  TuiAutoFocusModule,
  TuiActiveZoneModule,
  TuiCurrencyPipeModule,
  TuiHintModule,
  TuiBadgedContentModule,
  TuiStepperModule,
  TuiTabsModule,
  TuiToggleModule,
  TuiTextAreaModule,
  TuiTableModule,
  TuiNotificationModule,
  TuiDataListWrapperModule,
  TuiLetModule,
  TuiInputDateRangeModule,
  TuiTagModule,
  TuiInputFilesModule,
  TuiErrorModule,
  TuiFieldErrorPipeModule,
  TuiBadgeModule,
  TuiLineClampModule,
  TuiLabelModule,
  TuiExpandModule,
  TuiAccordionModule,
  TuiMultiSelectModule,
  TuiAppBarModule,
  TuiRootModule,
  TuiSheetModule,
  TuiBlockStatusModule,
  TuiThemeNightModule,
  TuiModeModule,
  TuiTilesModule,
  TuiDialogModule,
  PolymorpheusModule,
  TuiAlertModule,
];
